import {escape, stamp, badge, reason, condition, jobButton, duration, emptyMetric, terminal} from './components.js';

export function inspector(job, frame) {
  const parent = id=>frame.jobs.find(j=>j.id===id&&j.cluster===job.cluster);
  const children=frame.jobs.filter(j=>j.cluster===job.cluster&&j.dependencies.some(d=>d.id===job.id));
  return `<div class="inspector-heading"><div class="eyebrow">${escape(job.cluster)} / #${escape(job.id)}</div><h2 id="inspector-title">${escape(job.name)}</h2>${badge(job,frame)}<p>${escape(reason(job))}</p></div>
  <section class="inspector-section"><h3>Resources</h3><table class="resource-table"><thead><tr><th>Resource</th><th>Requested</th><th>Allocated</th></tr></thead><tbody>${[['GPUs','gpus'],['CPU cores','cpus'],['RAM','memory']].map(([label,key])=>`<tr><th>${label}</th><td>${escape(job.requested?.[key]??'Not recorded')}</td><td>${escape(job.allocated?.[key]??'Unassigned')}</td></tr>`).join('')}</tbody></table><p class="muted">${job.node?`Node ${escape(job.node)} · physical GPU slots not collected`:'Resources will be assigned by the scheduler.'}</p></section>
  <section class="inspector-section"><h3>Dependencies</h3>${job.dependency_expression?`<p class="mono">${escape(job.dependency_expression)}</p><p class="muted">Scheduler expression, preserved without simplifying its conditions.</p>`:''}${job.dependencies.length?job.dependencies.map(d=>`<div class="dependency-step"><span class="dependency-line" aria-hidden="true">↳</span><div><small>${escape(condition(d.condition))}</small>${parent(d.id)?jobButton(parent(d.id)):`<strong>#${escape(d.id)} · outside recording</strong>`}</div><span class="muted">${parent(d.id)?escape(parent(d.id).state.toLowerCase()):'Unknown'}</span></div>`).join(''):job.dependency_expression?'':'<p class="muted">No dependency captured. Earlier satisfied conditions may be absent.</p>'}
  ${children.length?`<h4>Downstream jobs</h4>${children.map(j=>`<div class="dependency-step"><span aria-hidden="true">→</span><div>${jobButton(j)}<small>${escape(condition(j.dependencies.find(d=>d.id===job.id).condition))}</small></div>${badge(j,frame)}</div>`).join('')}` : ''}
  <p class="small-note">Conditions make jobs eligible; resource availability still determines when they start.</p></section>
  <section class="inspector-section"><h3>Recorded timing</h3><dl class="detail-list">${[['Submitted',stamp(job.submitted_at)],['Actual start',stamp(job.started_at)],['Actual end',job.ended_at?stamp(job.ended_at):terminal(job)?'Not recorded':'Not ended / not observed'],['Elapsed',duration(job,frame)],['Wall-time limit',job.time_limit],['Last observation',stamp(job.observed_at)],['Exit code',job.exit_code??'Not terminal']].map(([label,value])=>`<div><dt>${label}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl></section>
  <section class="inspector-section"><h3>Utilization</h3><div class="missing-grid inspector-metrics">${emptyMetric('GPU / VRAM','No per-job device attribution')}${emptyMetric('CPU / RAM','See cluster telemetry for host measurements')}</div></section>`;
}
