import {escape,stamp} from './components.js';

export function inventory(frame) {
  if(!frame.inventory) return '<div class="empty">Node inventory unavailable for this observation.</div>';
  return `<section class="panel"><div class="panel-heading"><h2>Node inventory <span class="count">${frame.inventory.length}</span></h2><span class="muted">Visible to configured Slurm credentials</span></div><div class="table-scroll"><table><thead><tr><th>Node</th><th>State</th><th>CPU capacity</th><th>RAM capacity</th><th>GPU / generic resources</th><th>Allocated generic resources</th></tr></thead><tbody>${frame.inventory.map(n=>`<tr><td><strong>${escape(n.name)}</strong><small>${escape(n.architecture||'Architecture not reported')}</small></td><td>${escape(n.state)}</td><td>${n.cpus??'—'}</td><td>${n.memory_mib===null?'—':`${n.memory_mib} MiB`}</td><td class="mono">${escape(n.gres||'None reported')}</td><td class="mono">${escape(n.gres_used||'None reported')}</td></tr>`).join('')}</tbody></table></div></section><div class="coverage-strip">Slurm reports configured resources. Device UUIDs and actual usage come from telemetry; exporter targets are kept separate until their identities are explicitly mapped.</div>`;
}
function trend(frames,index,metric) {
  const values=frames.slice(0,index+1).map(f=>f.metrics?.find(m=>m.kind===metric.kind&&m.target===metric.target&&m.device===metric.device&&m.series===metric.series)?.value);
  const valid=values.filter(v=>v!==undefined),max=Math.max(1,...valid),min=Math.min(0,...valid);
  const circles=values.map((v,i)=>v===undefined?'':`<circle cx="${4+i/Math.max(1,values.length-1)*112}" cy="${28-(v-min)/(max-min)*24}" r="2" fill="currentColor"/>`).join('');
  return `<svg viewBox="0 0 120 32" class="metric-trend" role="img" aria-label="${escape(metric.kind)} observed samples; gaps are unknown">${circles}</svg>`;
}
export function telemetry(session,index) {
  const metrics=session.frames[index].metrics;
  if(!metrics) return '<section class="panel source-panel"><h2>Hardware telemetry</h2><p class="muted">No successful telemetry collection for this observation. Check Available data for connection status.</p></section>';
  if(!metrics.length) return '<section class="panel source-panel"><h2>Hardware telemetry</h2><p>No matching exporter series returned. Zero series does not mean zero usage.</p></section>';
  return `<section class="panel"><div class="panel-heading"><h2>Hardware telemetry</h2><span class="muted">Exporter targets · not per-job attribution</span></div><div class="table-scroll"><table><thead><tr><th>Target / GPU UUID</th><th>Measurement</th><th>Value</th><th>Recent observations</th><th>Prometheus result time</th></tr></thead><tbody>${metrics.map(m=>`<tr><td>${escape(m.target)}<small class="mono">${escape(m.device||'Host metric')}</small></td><td>${escape(m.kind)}</td><td class="mono">${Number(m.value).toLocaleString('en-GB',{maximumFractionDigits:1})}</td><td>${trend(session.frames,index,m)}</td><td>${stamp(m.sampled_at)}</td></tr>`).join('')}</tbody></table></div></section>`;
}
export function liveData(session,update) {
  const source=(name,h,enabled=true)=>`<tr><td>${name}</td><td>${enabled?(h.error?'Unavailable':h.last_success?'Connected':'Connecting'):'Not configured'}</td><td>${stamp(h.last_success)}</td><td>${escape(h.error||'—')}</td></tr>`;
  return `<section class="panel source-panel"><div class="section-title"><h2>${escape(session.cluster)} connection</h2><a href="/api/session" class="button" download="slurm-lens-live.json">Export history</a></div><p>Read-only Slurm REST v0.0.45. Sources are collected centrally, then streamed to this browser. Job visibility follows the configured credential.</p><p>${update.poll_seconds}s minimum interval between collections · up to ${update.history_frames} observations in memory. Restart clears history; export to retain it. Queries are not an atomic snapshot across sources.</p></section><section class="panel"><div class="table-scroll"><table><thead><tr><th>Source</th><th>Status</th><th>Last successful collection</th><th>Error</th></tr></thead><tbody>${source('Scheduler + node inventory',update.scheduler)}${source('Prometheus / exporters',update.telemetry,update.telemetry_enabled)}</tbody></table></div></section><div class="coverage-strip">Running-job end times and future placements are not predictions. Dependency expressions are shown verbatim; complex conditions are not simplified. Jobs disappearing from the scheduler retain their last observation, not an inferred completion.</div>`;
}
